FROM node:8-jessie

WORKDIR "/opt/app"

COPY . ./
RUN npm install
RUN npm run build

# Expose default port
EXPOSE 3000

RUN npm install --quiet

# Execute default startup command
CMD [ "npm", "run", "start" ]
